log_level: "info"

core:
  log_filename: "kafe.log"

  minimizers:
    default_minimizer: "iminuit"
    minuit:
      log_filename: "minuit.log"
      print_level: -1

  fitters:
    default_fitter: "nexus_fitter"


fit:
  log_filename: "fit.log"

  plot:
    axis_labels:
      x: '$x$'
      y: '$y$'

    style: !include plot_style_color.yaml